include ../../stdmk/stdmk_nt

EXE = 	Client.exe Server.exe 

all: $(EXE)

clean:
	del *.obj
	del *.exe
	del *_c.cpp
	del *_s.cpp
	del *.hh
	del *.log
	del *.out
	del *.ilk
	del *.pdb

#
# "Map" specific make rules
#

Map_s.cpp Map_s.hh Map_c.cpp Map_c.hh: Map.idl
	$(ORBCC) Map.idl

Client.exe: Map_c.hh Map_c.obj Client.obj 
	$(LINK_EXE) /out:Client.exe Client.obj \
	Map_c.obj $(LIBORB) $(STDCC_LIBS)

Server.exe: Map_c.hh Map_s.hh Map_s.obj Map_c.obj Server.obj
	$(LINK_EXE) /out:Server.exe Server.obj \
	Map_s.obj Map_c.obj $(LIBORB) $(STDCC_LIBS)
