//
//    Copyright (C) 2001 AT&T Laboratories Cambridge Ltd.
//
//    This file is part of the OMNI Testsuite.
//
//    The testsuite is free software; you can redistribute it and/or
//    modify it under the terms of the GNU Library General Public
//    License as published by the Free Software Foundation; either
//    version 2 of the License, or (at your option) any later version.
//
//    This library is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//    Library General Public License for more details.
//
//    You should have received a copy of the GNU Library General Public
//    License along with this library; if not, write to the Free
//    Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
//    02111-1307, USA
//
//
// From: Renzo Tomaselli <renzo.tomaselli@tecnotp.it>
// To: Omniorb list <omniorb-list@uk.research.att.com>
// Subject: [omniORB] IDL porting 2.8 -> 3.0
//
// http://www.uk.research.att.com/omniORB/archives/2000-07/0116.html

// omniidl failed to follow typedef chains to determine the actual
// inherited interfaces in several places.

module M1 {
    interface I1 {};
};
module M2 {
    typedef M1::I1 I1;
    interface I2 : M2::I1 {};
};
