//
//    Copyright (C) 2001 AT&T Laboratories Cambridge Ltd.
//
//    This file is part of the OMNI Testsuite.
//
//    The testsuite is free software; you can redistribute it and/or
//    modify it under the terms of the GNU Library General Public
//    License as published by the Free Software Foundation; either
//    version 2 of the License, or (at your option) any later version.
//
//    This library is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//    Library General Public License for more details.
//
//    You should have received a copy of the GNU Library General Public
//    License along with this library; if not, write to the Free
//    Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
//    02111-1307, USA
//
//
#ifndef __SEQ3_IDL__
#define __SEQ3_IDL__

#include "testecho.idl"

typedef sequence <Echo> seq_echo;
typedef sequence <sequence<Echo> > seqseq_echo;
typedef sequence <sequence<sequence<Echo> > > seqseqseq_echo;

typedef sequence <Echo,10> seq_echo_10;
typedef sequence <sequence<Echo,10>,10> seqseq_echo_10_10;
typedef sequence <sequence <sequence<Echo,10>,10>,10> seqseq_echo_10_10_10;

interface Exercise3 {
  seq_echo dump_seq_echo(in seq_echo a1, 
			 inout seq_echo a2,
  			 out seq_echo a3);
  seqseq_echo dump_seqseq_echo(in seqseq_echo a1, 
			       inout seqseq_echo a2, 
			       out seqseq_echo a3);
  seqseqseq_echo dump_seqseqseq_echo(in seqseqseq_echo a1, 
				     inout seqseqseq_echo a2,
  				     out seqseqseq_echo a3);

  seq_echo_10 dump_seq_echo_10(in seq_echo_10 a1, 
			       inout seq_echo_10 a2,
			       out seq_echo_10 a3);
  seqseq_echo_10_10 dump_seqseq_echo_10(in seqseq_echo_10_10 a1, 
			       inout seqseq_echo_10_10 a2,
 			       out seqseq_echo_10_10 a3);
  seqseq_echo_10_10_10 dump_seqseqseq_echo_10(in seqseq_echo_10_10_10 a1, 
				     inout seqseq_echo_10_10_10 a2, 
				     out seqseq_echo_10_10_10 a3);
};

#endif
