include ../stdmk_nt

EXE = 	Client.exe Server.exe 

all: $(EXE)

clean:
	del *.obj
	del *.exe
	del *_c.cpp
	del *_s.cpp
	del *.hh
	del *.log
	del *.out
	del *.ilk
	del *.pdb

#
# "Printer" specific make rules
#

Printer_c.cpp: Printer.idl
	$(ORBCC) -type_code_info Printer.idl

Printer_s.cpp: Printer.idl
	$(ORBCC) -type_code_info Printer.idl

Client.exe: Printer_c.obj Client.obj 
	$(LINK_EXE) /out:Client.exe Client.obj \
	Printer_c.obj $(LIBORB) $(STDCC_LIBS)

Server.exe: Printer_s.obj Printer_c.obj Server.obj
	$(LINK_EXE) /out:Server.exe Server.obj \
	Printer_s.obj Printer_c.obj $(LIBORB) $(STDCC_LIBS)
