interface FragTest {

  struct Payload {
    sequence<octet> o;
    double          d;  // Vary length of o to test if the ORB still 
    // maintains that d is properly aligned.
  };

  typedef sequence <Payload> Payloads;

  // Vary the no. of elements in the argument to test the GIOP fragmentation
  // code.
  Payloads bounce(in Payloads arg);

  // vary the size of string to exercise zero-copy marshalling with
  // fragmentation
  string bounce_string(in string arg);
};
