//
//    Copyright (C) 2001 AT&T Laboratories Cambridge Ltd.
//
//    This file is part of the OMNI Testsuite.
//
//    The testsuite is free software; you can redistribute it and/or
//    modify it under the terms of the GNU Library General Public
//    License as published by the Free Software Foundation; either
//    version 2 of the License, or (at your option) any later version.
//
//    This library is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//    Library General Public License for more details.
//
//    You should have received a copy of the GNU Library General Public
//    License along with this library; if not, write to the Free
//    Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
//    02111-1307, USA
//
//
// anyStructTest.idl
//

struct structLong
{
long l;
short s;
};

struct structDouble1
{
double d;
long l;
};

struct structDouble2
{
short l;
double d;
};

struct structVariable
{
string str;
double d;
};


typedef sequence<structVariable> seqStruct;
typedef structVariable arrayStruct[2];

struct structSequence
{
seqStruct s;
double d;
};

struct structArray
{
arrayStruct ar;
double d;
};

struct structStruct
{
double d;
structSequence st;
};



interface anyStructTest
{
any testOp(in any a, inout any b, out any d);
};


#if 0
//?? We ought to add and test types like the following:
// (These have caused problems in the past).

struct structS1 {
  short a;
  short b;
  long c;
  short d;
};

typedef sequence<structS1> seqStructS1;
typedef structS1 a5structS1[5];
#endif
