//
//    Copyright (C) 2001 AT&T Laboratories Cambridge Ltd.
//
//    This file is part of the OMNI Testsuite.
//
//    The testsuite is free software; you can redistribute it and/or
//    modify it under the terms of the GNU Library General Public
//    License as published by the Free Software Foundation; either
//    version 2 of the License, or (at your option) any later version.
//
//    This library is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//    Library General Public License for more details.
//
//    You should have received a copy of the GNU Library General Public
//    License along with this library; if not, write to the Free
//    Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
//    02111-1307, USA
//
//
// struct1.idl
//

module moduleOne
{
	enum anEnum
	{
	ZERO,ONE,TWO
	};
};

struct structLong
{
long l;
short s;
};

struct structDouble1
{
double d;
long l;
};

module outer
{
	struct structDouble2
	{	
	short l;
	double d;
	};
};

struct structVariable
{
string str;
double d;
};

// changed from declaration from definition because of problems with 
// Digital C++

interface aninterface1
{
void op(); 
}; 


struct structEnum
{
moduleOne::anEnum instance_of_enum;
string astr;
aninterface1 anintf1;
};

interface aninterface2
{
void op();
};

struct structInterface2
{
boolean b;
aninterface2 anintf2;
};
