//
//    Copyright (C) 2001 AT&T Laboratories Cambridge Ltd.
//
//    This file is part of the OMNI Testsuite.
//
//    The testsuite is free software; you can redistribute it and/or
//    modify it under the terms of the GNU Library General Public
//    License as published by the Free Software Foundation; either
//    version 2 of the License, or (at your option) any later version.
//
//    This library is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//    Library General Public License for more details.
//
//    You should have received a copy of the GNU Library General Public
//    License along with this library; if not, write to the Free
//    Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
//    02111-1307, USA
//
//
//**************************************************************************
//
// NAME :  test1.idl  
// VERSION: Orbix ::RELNO::
//
//                 Copyright (c) 1993-6 Iona Technologies Ltd.
//                          All Rights Reserved
//
//        THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Iona Technologies
//
//        The copyright notice above does not evidence any
//        actual or intended publication of such source code.
//
// DESCRIPTION: IDL for any_demo
//
//
//****************************************************************************

// IDL file for the testAny demo code.  The IDL interface 'testAny' defines
// two operations.  op1 takes a parameter of type 'any';  op2 has an out
// parameter of type 'any'.
 

// define a struct so that we can pass a sequence of structs for the 'any'
// parameter.

struct structS  {
   long i;
   float f;
};


// define a typedef to force sequence tc_ code generation
//
typedef sequence<structS> seqStruct;


interface testAny {
    void op1 (in any x);

    void op2 (out any x);
};
