// **********************************************************************
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

//
// IDL Context test. Valid for ORBacus 3, ORBacus 4
//

module ORBTest_Context
{
    typedef sequence<string> StringSequence;

    interface Intf
    {
	StringSequence
	opContext(
	    in string pattern
	)
	    context ("A*", "C*", "X", "Z");
    };
}; // module ORBTest_Context
