//
//    Copyright (C) 2001 AT&T Laboratories Cambridge Ltd.
//
//    This file is part of the OMNI Testsuite.
//
//    The testsuite is free software; you can redistribute it and/or
//    modify it under the terms of the GNU Library General Public
//    License as published by the Free Software Foundation; either
//    version 2 of the License, or (at your option) any later version.
//
//    This library is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//    Library General Public License for more details.
//
//    You should have received a copy of the GNU Library General Public
//    License along with this library; if not, write to the Free
//    Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
//    02111-1307, USA
//
//
// array1a.idl
//

typedef long arrayLong[3];
typedef arrayLong aliasArrayLong;

typedef string arrayString[10];

typedef long multiLong[3][473];
typedef string multiString[10][30];


module outer1
{
typedef long modLong[3];
typedef long multiModLong[3][5];
};

interface intf1;

typedef intf1 arrayIntf1[10];
typedef intf1 multiIntf1[10][30];

struct blah
{
long embeddedArrayLong[10];
string embeddedArrayString[10];
};

typedef blah arrayBlah[10];
typedef blah multiBlah[10][30];

typedef arrayBlah aliasArrayBlah;
typedef arrayBlah multiArrayBlah[40];

interface intf1 {
void op();
};

enum discrimEnum
{
A,B,C
};

union unionLong switch(long)
{
case 1: long l;
case 2: short s;
};

union unionDouble1 switch(long)
{
case 1: double d;
default: long l;
};


module outer
{
union unionVariable switch(discrimEnum)
{
case A: string str;
case B: double d;
};
};


struct testStruct
{
long l;
double d;
};

union unionStruct switch(long)
{
case 1: double d;
case 2: testStruct tS;
};


interface testAnyUnion
{
any testOp(in any a, inout any b, out any d);
oneway void destroy();
};


union unionDouble2 switch(discrimEnum)
{
case A: testAnyUnion tAU;
case C: double d;
default: unsigned long ul;
};

interface intf2
{
void anop();
};

