// **********************************************************************
//
// Copyright (c) 2001
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Subset of IOP definitions required for these tests

#pragma prefix "omg.org"

module IOP
{

typedef unsigned long ComponentId;
typedef unsigned long ServiceId;

};
