
all :
	@echo "You must specify a target"


nt :
	$(MAKE) -f Makefile.nt 

java :
	$(MAKE) -f Makefile.java 

cpp :
	$(MAKE) -f Makefile.cpp

clean_java :
	$(MAKE) -f Makefile.java clean

clean_cpp :
	$(MAKE) -f Makefile.cpp clean

clean_nt :
	$(MAKE) -f Makefile.nt clean

